/*CORDIC SQRT SQUARE
*
* BY EARL T (ET)
* THIS IS FIRST GENRAL SQUARE ALGO A FULL POWER WILL BE IMPLEMENTED
* LATER IT IS ACOMPLISHED BY USEING THE LOG AND EXP FUNCTIONS FORMULA
* A^2 = EXP(LOG(A)<<1) = EXP(LOG(A)*2)
* this being true means to find the square root of a number you only 
* have to inverse the bit shift so that EXP(LOG(A)>>1)=SQRT(A) NOTE:
* THIS METHOD IS NOT EXCLUSIVLY CORDIC IN NATURE HOWEVER THIS 
* VERSION USES THE CORDIC EXPX AND LOGX 
* THE INPUTS OF THESE IS KINDA LIMITED NOT SURE YET WHERE THE LIMITS ARE YET IE
* THIS IS STILL EXPERIMENTAL
* FAR TESTS AS IS SHOWS AT 10^2 COMES TO 100.546875 SO OVER .5 OFF I'M GOING 
* TO WORK ON THAT IN THE FUTURE FOR NOW  I THINL IM OK AS NUMBERS IN SPHEREICAL 
* GEOMETRY ARE KINDA LIMITED TO UNDER 4 OR 5 AT ANY ONE POINT IN THE EQUATION
* NOTE I HAVE NOT DONE ALL EQ STEP BY STEP SO THIS COULD BE WRONG WE WILL SEE
* REGARDLESS I WILL COME BACK AND TRY AND RECTIFY SOME OF THESE ISSUES GOD WILLING  
*/
#include "../include/CORDIC.h"

/*IM GONNA ADD LIMITS IM PUTTING IT AT 7 IM ALSO GOING TO TRY TO ADJUST THE EXP 
*/
//IT SHIPS CUS I'M TIRED ACURCCY NEEDS WORK EVEN FOR LOW NUMBERS AND LESS THEN 1 
// JUST DONT WORK BUT ILL WORK ON IT LATER IM SICK OF TWEAKING SHIT RIGHT NOW
fix CORDIC_sqx( fix x ){
	return CORDIC_expx((CORDIC_logx(x)<<1));

}
//AS ALWAYS X VERSION MUCH MORE EFFICENT 
float CORDIC_sq( float ex ){
	fix x = to_fix(ex);
	return to_float(CORDIC_sqx(x));

}
/* I HAVE YET TO TEST THESE FOR ACURACY ALTHO THE METHOD IS SOUND I MAY SUFFER FROM INACURACY MULTIPLIED FROM THE ORIGONAL 
* FUNCTIONS IN WHITCH CASE I WILL HAVE TO WORK THAT OUT WITCH WILL MOST LIKELY REQUIRE USE OF 64 BIT INTEGERS AS FIX POINT ALSO NOTE
* THE 8.3 UPPER LIMIT TO THE INPUT OF EXPX IS STILL TRUE ALL THOU
*/
fix CORDIC_sqrtx( fix x ){
	return CORDIC_expx((CORDIC_logx(x)>>1));

}
float CORDIC_sqrt( float ex ){
	fix x = to_fix(ex) ;
	return to_float(CORDIC_sqrtx(x)) ;
}